services:
  mongodb:
    image: mongo:7
    container_name: shieldmsg-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - shieldmsg_mongo_data:/data/db

volumes:
  shieldmsg_mongo_data:
